#!/usr/bin/env python
# -*- coding: UTF-8 -*-
import logging
import time
import os
import sys
sys.path.insert(0, '/home/mario/thinetic/github/server-stats-system-agent')

import sssa
from sssa.main import ServerStatsSystemAgent

if __name__ == '__main__':
    if not os.path.isfile(sssa.CONFIG_INI):
        print "ERROR: /etc/sssa.conf not found"
        sys.exit(1)
    #
    logger = logging.getLogger("")
    logger.setLevel(logging.DEBUG)
    formatter = logging.Formatter("%(asctime)s - %(name)16s - %(levelname)s - %(message)s")

    if "--debug" in sys.argv:
        ch = logging.StreamHandler(sys.stdout)
        ch.setLevel(logging.DEBUG)
        ch.setFormatter(formatter)
        logger.addHandler(ch)
        logger.setLevel(logging.DEBUG)
    else:
        handler = logging.FileHandler()
        handler = logging.handlers.RotatingFileHandler(sssa.SSSA_LOG,
                                                       maxBytes=10 * 1024 * 1024,
                                                       backupCount=10)
        handler.setFormatter(formatter)
        logger.addHandler(handler)
    #
    #
    app = ServerStatsSystemAgent()
    app.run()
